// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DulceFacil.Infraestructura.DataAccess;

public partial class dulceFacilDBContext : DbContext
{
    public dulceFacilDBContext()
    {
    }

    public dulceFacilDBContext(DbContextOptions<dulceFacilDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<cliente> cliente { get; set; }

    public virtual DbSet<detalle_pedido> detalle_pedido { get; set; }

    public virtual DbSet<pedido> pedido { get; set; }

    public virtual DbSet<persona> persona { get; set; }

    public virtual DbSet<producto> producto { get; set; }

    public virtual DbSet<punto_venta> punto_venta { get; set; }

    public virtual DbSet<reparto> reparto { get; set; }

    public virtual DbSet<rol> rol { get; set; }

    public virtual DbSet<usuario> usuario { get; set; }

    public virtual DbSet<zona> zona { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-C05PO3B\\SQLEXPRESS;Initial Catalog=dulceFacilDB;Integrated Security=True;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<cliente>(entity =>
        {
            entity.HasKey(e => e.id_cliente).HasName("PK__cliente__677F38F51F98463A");

            entity.Property(e => e.tipo).HasMaxLength(50);

            entity.HasOne(d => d.id_personaNavigation).WithMany(p => p.cliente)
                .HasForeignKey(d => d.id_persona)
                .HasConstraintName("FK__cliente__id_pers__6D0D32F4");

            entity.HasOne(d => d.id_zonaNavigation).WithMany(p => p.cliente)
                .HasForeignKey(d => d.id_zona)
                .HasConstraintName("FK__cliente__id_zona__6E01572D");
        });

        modelBuilder.Entity<detalle_pedido>(entity =>
        {
            entity.HasKey(e => e.id_detalle_pedido).HasName("PK__detalle___C08768CF075AD13D");

            entity.Property(e => e.precio_unitario).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.total).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_pedidoNavigation).WithMany(p => p.detalle_pedido)
                .HasForeignKey(d => d.id_pedido)
                .HasConstraintName("FK__detalle_p__id_pe__797309D9");

            entity.HasOne(d => d.id_productoNavigation).WithMany(p => p.detalle_pedido)
                .HasForeignKey(d => d.id_producto)
                .HasConstraintName("FK__detalle_p__id_pr__7A672E12");
        });

        modelBuilder.Entity<pedido>(entity =>
        {
            entity.HasKey(e => e.id_pedido).HasName("PK__pedido__6FF01489F86785B4");

            entity.Property(e => e.estado).HasMaxLength(50);
            entity.Property(e => e.fecha_entrega_estimada).HasColumnType("datetime");
            entity.Property(e => e.fecha_pedido).HasColumnType("datetime");

            entity.HasOne(d => d.id_clienteNavigation).WithMany(p => p.pedido)
                .HasForeignKey(d => d.id_cliente)
                .HasConstraintName("FK__pedido__id_clien__76969D2E");
        });

        modelBuilder.Entity<persona>(entity =>
        {
            entity.HasKey(e => e.id_persona).HasName("PK__persona__228148B0CDDCB2A5");

            entity.Property(e => e.apellido).HasMaxLength(100);
            entity.Property(e => e.direccion).HasMaxLength(200);
            entity.Property(e => e.email).HasMaxLength(100);
            entity.Property(e => e.nombre).HasMaxLength(100);
            entity.Property(e => e.telefono).HasMaxLength(20);
        });

        modelBuilder.Entity<producto>(entity =>
        {
            entity.HasKey(e => e.id_producto).HasName("PK__producto__FF341C0DA24779B0");

            entity.Property(e => e.descripcion).HasMaxLength(500);
            entity.Property(e => e.nombre).HasMaxLength(100);
            entity.Property(e => e.precio).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<punto_venta>(entity =>
        {
            entity.HasKey(e => e.id_punto_venta).HasName("PK__punto_ve__06416536231DE0DA");

            entity.Property(e => e.direccion).HasMaxLength(200);
            entity.Property(e => e.nombre).HasMaxLength(100);
            entity.Property(e => e.tipo_negocio).HasMaxLength(100);

            entity.HasOne(d => d.id_clienteNavigation).WithMany(p => p.punto_venta)
                .HasForeignKey(d => d.id_cliente)
                .HasConstraintName("FK__punto_ven__id_cl__71D1E811");

            entity.HasOne(d => d.id_zonaNavigation).WithMany(p => p.punto_venta)
                .HasForeignKey(d => d.id_zona)
                .HasConstraintName("FK__punto_ven__id_zo__70DDC3D8");
        });

        modelBuilder.Entity<reparto>(entity =>
        {
            entity.HasKey(e => e.id_reparto).HasName("PK__reparto__1EFBEFBC3500A222");

            entity.Property(e => e.estado).HasMaxLength(50);
            entity.Property(e => e.vehiculo).HasMaxLength(100);

            entity.HasOne(d => d.id_pedidoNavigation).WithMany(p => p.reparto)
                .HasForeignKey(d => d.id_pedido)
                .HasConstraintName("FK__reparto__id_pedi__7F2BE32F");

            entity.HasOne(d => d.id_personaNavigation).WithMany(p => p.reparto)
                .HasForeignKey(d => d.id_persona)
                .HasConstraintName("FK__reparto__id_pers__7D439ABD");

            entity.HasOne(d => d.id_zonaNavigation).WithMany(p => p.reparto)
                .HasForeignKey(d => d.id_zona)
                .HasConstraintName("FK__reparto__id_zona__7E37BEF6");
        });

        modelBuilder.Entity<rol>(entity =>
        {
            entity.HasKey(e => e.id_rol).HasName("PK__rol__6ABCB5E0586F2EB8");

            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<usuario>(entity =>
        {
            entity.HasKey(e => e.id_usuario).HasName("PK__usuario__4E3E04AD6A12F351");

            entity.Property(e => e.password_user)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.usuario1)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("usuario");

            entity.HasOne(d => d.id_personaNavigation).WithMany(p => p.usuario)
                .HasForeignKey(d => d.id_persona)
                .HasConstraintName("FK__usuario__id_pers__6754599E");

            entity.HasOne(d => d.id_rolNavigation).WithMany(p => p.usuario)
                .HasForeignKey(d => d.id_rol)
                .HasConstraintName("FK__usuario__id_rol__68487DD7");
        });

        modelBuilder.Entity<zona>(entity =>
        {
            entity.HasKey(e => e.id_zona).HasName("PK__zona__67C93611CC4A8012");

            entity.Property(e => e.descripcion).HasMaxLength(255);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}