// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.DataAccess;

public partial class cliente
{
    public int id_cliente { get; set; }

    public int? id_persona { get; set; }

    public string tipo { get; set; }

    public int? id_zona { get; set; }

    public virtual persona id_personaNavigation { get; set; }

    public virtual zona id_zonaNavigation { get; set; }

    public virtual ICollection<pedido> pedido { get; set; } = new List<pedido>();

    public virtual ICollection<punto_venta> punto_venta { get; set; } = new List<punto_venta>();
}