// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.DataAccess;

public partial class pedido
{
    public int id_pedido { get; set; }

    public DateTime? fecha_pedido { get; set; }

    public DateTime? fecha_entrega_estimada { get; set; }

    public int? id_cliente { get; set; }

    public string estado { get; set; }

    public virtual ICollection<detalle_pedido> detalle_pedido { get; set; } = new List<detalle_pedido>();

    public virtual cliente id_clienteNavigation { get; set; }

    public virtual ICollection<reparto> reparto { get; set; } = new List<reparto>();
}