// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.DataAccess;

public partial class persona
{
    public int id_persona { get; set; }

    public string nombre { get; set; }

    public string apellido { get; set; }

    public string telefono { get; set; }

    public string direccion { get; set; }

    public string email { get; set; }

    public virtual ICollection<cliente> cliente { get; set; } = new List<cliente>();

    public virtual ICollection<reparto> reparto { get; set; } = new List<reparto>();

    public virtual ICollection<usuario> usuario { get; set; } = new List<usuario>();
}