// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.DataAccess;

public partial class producto
{
    public int id_producto { get; set; }

    public string nombre { get; set; }

    public decimal? precio { get; set; }

    public string descripcion { get; set; }

    public int? stock { get; set; }

    public virtual ICollection<detalle_pedido> detalle_pedido { get; set; } = new List<detalle_pedido>();
}