// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.DataAccess;

public partial class punto_venta
{
    public int id_punto_venta { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public string tipo_negocio { get; set; }

    public int? id_zona { get; set; }

    public int? id_cliente { get; set; }

    public virtual cliente id_clienteNavigation { get; set; }

    public virtual zona id_zonaNavigation { get; set; }
}