// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.DataAccess;

public partial class reparto
{
    public int id_reparto { get; set; }

    public int? id_persona { get; set; }

    public string vehiculo { get; set; }

    public DateOnly? fecha { get; set; }

    public int? id_zona { get; set; }

    public int? id_pedido { get; set; }

    public string estado { get; set; }

    public virtual pedido id_pedidoNavigation { get; set; }

    public virtual persona id_personaNavigation { get; set; }

    public virtual zona id_zonaNavigation { get; set; }
}