// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.DataAccess;

public partial class rol
{
    public int id_rol { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<usuario> usuario { get; set; } = new List<usuario>();
}