// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.DataAccess;

public partial class usuario
{
    public int id_usuario { get; set; }

    public int? id_persona { get; set; }

    public string usuario1 { get; set; }

    public string password_user { get; set; }

    public int? id_rol { get; set; }

    public virtual persona id_personaNavigation { get; set; }

    public virtual rol id_rolNavigation { get; set; }
}